account_register:
    path: /Account/Register
    defaults: { _controller: ScrumManagerApiBundle:Account:register }
    methods: [POST]

account_register:
    path: /Account/Login
    defaults: { _controller: ScrumManagerApiBundle:Account:login }
    methods: [POST]

account_update_one:
    path: /Account/UpdateOne
    defaults: { _controller: ScrumManagerApiBundle:Account:updateOne }
    methods: [POST]

account_change_password:
    path: /Account/ChangePassword
    defaults: { _controller: ScrumManagerApiBundle:Account:changePassword }
    methods: [POST]

account_retrieve_one:
    path: /Account/RetrieveOne
    defaults: { _controller: ScrumManagerApiBundle:Account:retrieveOne }
    methods: [POST]

account_deactivate:
    path: /Account/Deactivate
    defaults: { _controller: ScrumManagerApiBundle:Account:deactivate }
    methods: [POST]

account_reset_password:
    path: /Account/ResetPassword
    defaults: { _controller: ScrumManagerApiBundle:Account:resetPassword }
    methods: [POST]

account_new_password:
    path: /Account/NewPassword
    defaults: { _controller: ScrumManagerApiBundle:Account:newPassword }
    methods: [POST]



testscreen_account_register:
    path: /testscreen/account/register
    defaults: { _controller: ScrumManagerApiBundle:AccountTestScreen:register }

testscreen_account_login:
    path: /testscreen/account/login
    defaults: { _controller: ScrumManagerApiBundle:AccountTestScreen:login }

testscreen_account_update_one:
    path: /testscreen/account/updateOne
    defaults: { _controller: ScrumManagerApiBundle:AccountTestScreen:updateOne }

testscreen_account_change_password:
    path: /testscreen/account/changePassword
    defaults: { _controller: ScrumManagerApiBundle:AccountTestScreen:changePassword }

testscreen_account_retrieve_one:
    path: /testscreen/account/retrieveOne
    defaults: { _controller: ScrumManagerApiBundle:AccountTestScreen:retrieveOne }

testscreen_account_deactivate:
    path: /testscreen/account/deactivate
    defaults: { _controller: ScrumManagerApiBundle:AccountTestScreen:deactivate }

testscreen_account_reset_password:
    path: /testscreen/account/resetPassword
    defaults: { _controller: ScrumManagerApiBundle:AccountTestScreen:resetPassword }

testscreen_account_new_password:
    path: /testscreen/account/newPassword
    defaults: { _controller: ScrumManagerApiBundle:AccountTestScreen:newPassword }