parameters:
  account.entity.class: ScrumManager\ApiBundle\Entity\Account
  account.service.class: ScrumManager\ApiBundle\Service\AccountService
  account.repository.class: ScrumManager\ApiBundle\Repository\AccountRepository

  email.entity.class: ScrumManager\ApiBundle\Entity\Email
  email.service.class: ScrumManager\ApiBundle\Service\EmailService
  email.repository.class: ScrumManager\ApiBundle\Repository\EmailRepository

  json.service.class: ScrumManager\ApiBundle\Service\JsonService

services:
  account.service:
    class: %account.service.class%
    arguments: [@validator, @doctrine.orm.entity_manager ]

  email.service:
    class: %email.service.class%
    arguments: [@validator, @doctrine.orm.entity_manager]

  json.service:
    class: %json.service.class%